modLoader="javafml"
loaderVersion="[4,)"
license="GNU LGPL V3.0"

[[mods]]
modId="nopoisonregen"
version="${file.jarVersion}"
displayName="No Poison with Regeneration"
displayURL="https://www.curseforge.com/minecraft/mc-mods/nmpr"
authors="kara2810x"
description='''
This mod makes it so that the potion effects poison and regenration cancel each other out.
'''
[[dependencies.nopoisonregen]]
modId="minecraft"
type="required"
versionRange="[1.21,1.22)"
ordering="NONE"
side="BOTH"
