# Project
version=3.5.0
group=com.nopoisonregen.main

# Common
minecraft_version=1.21.10

# NeoForge
neo_version=21.10.47-beta
neogradle.subsystems.parchment.minecraftVersion=1.21.10
neogradle.subsystems.parchment.mappingsVersion=2025.10.12
neogradle.subsystems.conventions.runs.create-default-run-per-type=false

# Fabric
fabric_version=0.137.0+1.21.10
fabric_loader_version=0.17.3
cloth_config_version=20.0.148
mod_menu_version=16.0.0-rc.1

# Mod options
mod_name=NMPR
mod_author=kara2810x
mod_id=nopoisonregen

#Publishing
curseforge_id=317853
modrinth_id=6UbQDdoj

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false